# Generated by Django 5.2.4 on 2025-07-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('second_name', models.CharField(max_length=25)),
                ('student_id', models.IntegerField()),
                ('teacher', models.CharField(choices=[('golshan', 'Golshan'), ('shahraki', 'Shahraki'), ('somedude', 'Somedude'), ('bruh', 'Bruh')], max_length=8)),
            ],
        ),
    ]
